[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x30\x66ile:///home/sheb/Videos/2026-07-04_21-15-51.mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\f\0\0\0&\0\0\x3\xbb\0\0\x4\x31\0\0\0\f\0\0\0&\0\0\x3\xbb\0\0\x4\x31\0\0\0\0\0\0\0\0\a\x80\0\0\0\f\0\0\0&\0\0\x3\xbb\0\0\x4\x31)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Mediainfo]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc4\0\0\0&\0\0\as\0\0\x4\x31\0\0\x3\xc4\0\0\0&\0\0\as\0\0\x4\x31\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc4\0\0\0&\0\0\as\0\0\x4\x31)

[OpenDialog]
advanced=false
netMRL=
size=@Size(639 400)

[RecentsMRL]
list=file:///home/sheb/Videos/2026-07-04_21-15-51.mp4
times=0
