; catppuccin-mocha.ini

[base]
default          = none
unknown-token    = 210,bold
commandseparator = none
redirection      = none
here-string-tri  = 223
here-string-text = 189
here-string-var  = 117,bg:18
exec-descriptor  = 223,bold
comment          = 60
correct-subtle   = 147
incorrect-subtle = 210
subtle-separator = 151
subtle-bg        = bg:235
secondary        = free
recursive-base   = 

[command-point]
reserved-word  = 183
subcommand     = 183
alias          = 151
suffix-alias   = 151
global-alias   = bg:111
builtin        = 151
function       = 151
command        = 151
precommand     = 151
hashed-command = 151
single-sq-bracket = 151
double-sq-bracket = 151
double-paren   = 223

[paths]
path          = 111
pathseparator = 
path-to-dir   = 111,underline
globbing      = 183,bold
globbing-ext  = 218

[brackets]
paired-bracket = bg:238
bracket-level-1 = 151,bold
bracket-level-2 = 223,bold
bracket-level-3 = 117,bold

[arguments]
optarg-string = 151
optarg-number = 216
single-hyphen-option   = 117
double-hyphen-option   = 117
back-quoted-argument   = none
single-quoted-argument = 151
double-quoted-argument = 151
dollar-quoted-argument = 151

[in-string]
; backslash in $'...'
back-dollar-quoted-argument           = 117
; backslash or $... in "..."
back-or-dollar-double-quoted-argument = 117

[other]
variable             = 147
assign               = none
assign-array-bracket = 151
history-expansion    = 183,bold

[math]
mathvar = 183,bold
mathnum = 216
matherr = 210

[for-loop]
forvar = none
fornum = 216
; operator
foroper = 183
; separator
forsep = 183,bold

[case]
case-input       = 151
case-parentheses = 223
case-condition   = bg:238
