# Effects
blur=0
shadows=0
border_radius=6
focused_opacity=1.0
unfocused_opacity=0.7

# Animations
animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=zoom
layer_animation_type_open=slide
layer_animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
fadein_begin_opacity=0.8
fadeout_begin_opacity=0.8
tag_animation_direction=1
zoom_initial_ratio=0.1
zoom_end_ratio=1
animation_duration_open=400
animation_duration_close=300
animation_duration_focus=300
animation_duration_move=500
animation_duration_tag=400

# Appearance
gappih=4
gappiv=4
gappoh=4
gappov=4
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=2
rootcolor=0x11111bff
bordercolor=0x313244ff
focuscolor=0xcba6f7ff
dropcolor=0x94e2d555
splitcolor=0xf38ba8ff
maximizescreencolor=0xf9e2afff
urgentcolor=0xf38ba8ff
scratchpadcolor=0xcba6f7ff
globalcolor=0xcba6f7ff
overlaycolor=0xf5c2e7ff

# Binds
bind=SUPER,m,quit
bind=SUPER,r,reload_config

# apps
bind=SUPER,Return,spawn,alacritty
bind=SUPER,b,spawn,chromium

# focus
bind=SUPER,w,focusdir,up
bind=SUPER,a,focusdir,left
bind=SUPER,s,focusdir,down
bind=SUPER,d,focusdir,right
bind=SUPER,Tab,toggleoverview,0
bind=SUPER+SHIFT,Tab,toggleoverview,1

# swap
bind=SUPER+SHIFT,w,exchange_client,up
bind=SUPER+SHIFT,a,exchange_client,left
bind=SUPER+SHIFT,s,exchange_client,down
bind=SUPER+SHIFT,d,exchange_client,right

# resize
bind=SUPER+ALT,w,resizewin,+0,+100
bind=SUPER+ALT,a,resizewin,-100,+0
bind=SUPER+ALT,s,resizewin,+0,-100
bind=SUPER+ALT,d,resizewin,+100,+0

# actions
bind=SUPER,q,killclient
bind=SUPER,e,minimized
bind=SUPER+SHIFT,e,restore_minimized
bind=SUPER,grave,toggle_scratchpad
bind=SUPER,f,togglemaximizescreen
bind=SUPER,v,togglefloating

# layouts
bind=SUPER,1,setlayout,scroller
bind=SUPER,2,setlayout,center_tile
bind=SUPER,3,setlayout,dwindle
bind=SUPER,4,setlayout,deck
bind=SUPER,5,setlayout,grid

# tags
bind=SUPER+ALT,1,view,1
bind=SUPER+ALT,2,view,2
bind=SUPER+ALT,3,view,3
bind=SUPER+ALT,4,view,4
bind=SUPER+ALT,5,view,5
bind=SUPER+ALT,6,view,6
bind=SUPER+ALT,7,view,7
bind=SUPER+ALT,8,view,8
bind=SUPER+ALT,9,view,9

# Autostart
exec-once=waybar
exec-once=mako
exec-once=wlr-randr --output HDMI-A-1 --mode 1920x1080@74.989998Hz

# Keyboard
repeat_rate=25
repeat_delay=600
numlockon=1
xkb_rules_layout=us

# Trackpad 
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
mouse_natural_scrolling=0
trackpad_natural_scrolling=0
scroll_method=2 # edge
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1
mouse_accel_profile=0
mouse_accel_speed=0.0

# Layouts
# tags
tagrule=id:1,layout_name:scroller
tagrule=id:3,layout_name:center_tile
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:deck
tagrule=id:6,layout_name:grid
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# scroller
scroller_structs=12
scroller_default_proportion=0.5
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
edge_scroller_focus_allow_speed=0.0
scroller_ignore_proportion_single=0
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

# master
new_is_master=1
smartgaps=0
default_mfact=0.6
default_nmaster=1

# dwindle
dwindle_smart_split=0
dwindle_drop_simple_split=1
dwindle_manual_split=0
dwindle_hsplit=1
dwindle_vsplit=1
dwindle_preserve_split=1

# overview
hotarea_size=2
enable_hotarea=1
hotarea_corner=2 # bottom left
ov_tab_mode=1
ov_no_resize=1
overviewgappi=5
overviewgappo=30

# Misc
xwayland_persistence=1
syncobj_enable=0
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
sloppyfocus=1
warpcursor=1
focus_cross_monitor=1
focus_cross_tag=1
scratchpad_cross_monitor=1
single_scratchpad=1
circle_layout=scroller,center_tile
enable_floating_snap=1
snap_distance=50
cursor_size=24
cursor_theme=catppuccin-mocha-mauve-cursors
cursor_hide_timeout=0
drag_tile_to_tile=1
drag_corner=4
drag_warp_cursor=0
